project:
  type: website
  render:
    - index.qmd
    - slides-data/api.qmd

lang: fr

website:
  title: "Atelier du `SSPHub`"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: "slides-data/api.qmd"
        text: API


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-annotations: hover
    code-link: true

execute:
  cache: true
